### ISSUE TITLE
Can't run pyopencl examples: 'Buffer' object has no attribute 'ptr'

### ISSUE THREAD

**Issue by nh2** [diku-dk/futhark#470]
I'm using Ubuntu 16.04 (and accordingly, the `python-pyopencl` that it ships), futhark commit 6f777b711b4c773af8916ab3ecf57cede8f37e4f.

```
% ~/src/futhark/.stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/futhark-pyopencl/futhark-pyopencl fact.fut

% echo 10 | ./fact
Traceback (most recent call last):
  File "./fact", line 2281, in <module>
    entry_point_fun()
  File "./fact", line 2263, in entry_main
    scalar_out_2606 = self.futhark_main(n_2517)
  File "./fact", line 2214, in futhark_main
    mem_2597 = opencl_alloc(self, bytes_2595, "mem_2597")
  File "./fact", line 172, in opencl_alloc
    return FutharkBuffer(self, min_size, tag, cl.Buffer(self.ctx, cl.mem_flags.READ_WRITE, min_size))
  File "./fact", line 188, in __init__
    self.ptr = buf.ptr
AttributeError: 'Buffer' object has no attribute 'ptr'
```

Also, just to double-check: The Python expected by futhark is Python 2, right?

**Comment by Athas** [comment]
Futhark is supposed to work with both Python 2 and 3.

The problem you are encountering is (I think) that your PyOpenCL is too
old.  But maybe we are doing things in the generated PyOpenCL code that
we really should not - I found it a bit unclear what's part of the
external interface and what's supposed to be an implementation detail.

I will take a closer look at exactly what's going on, and what we expect
from PyOpenCL.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
From what I can determine, Futhark will definitely work with recent versions of PyOpenCL - I have tried it on both 2017.1 and 2018.1 (installed via `pip`).  If these are easy to install on whatever system you are using (`sudo pip install pyopencl`, probably preceded by installing Python development headers), I think that's fine.  

If this is not practical, then I suppose we can roll back the change that caused this stricter PyOpenCL version requirement (the Python version of the [new allocator](https://futhark-lang.org/blog/2018-01-28-how-futhark-manages-gpu-memory.html)).  This will impact performance negatively, but the primary purpose of the Python backend is in any case convenience, not performance, so it would be excusable.

**Comment by nh2** [comment]
Ubuntu 16.04 [has pyopencl 2015.1-2build3](https://packages.ubuntu.com/xenial/python-pyopencl).

I've done a quick test with a newer version (currently `pyopencl-2018.1`):

```
niklas@ares ~/src/fut % virtualenv --system-site-packages env
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/niklas/src/fut/env/bin/python2
Also creating executable in /home/niklas/src/fut/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
niklas@ares ~/src/fut % source env/bin/activate
(env) niklas@ares ~/src/fut % ~/src/futhark/.stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/futhark-pyopencl/futhark-pyopencl fact.fut && echo "100" | ./fact
Traceback (most recent call last):
  File "./fact", line 2281, in <module>
    entry_point_fun()
  File "./fact", line 2263, in entry_main
    scalar_out_2606 = self.futhark_main(n_2517)
  File "./fact", line 2214, in futhark_main
    mem_2597 = opencl_alloc(self, bytes_2595, "mem_2597")
  File "./fact", line 172, in opencl_alloc
    return FutharkBuffer(self, min_size, tag, cl.Buffer(self.ctx, cl.mem_flags.READ_WRITE, min_size))
  File "./fact", line 188, in __init__
    self.ptr = buf.ptr
AttributeError: 'Buffer' object has no attribute 'ptr'
(env) 1 niklas@ares ~/src/fut % pip install pyopencl
Requirement already satisfied: pyopencl in /usr/lib/python2.7/dist-packages
(env) niklas@ares ~/src/fut % pip install -U pyopencl
Collecting pyopencl
  Downloading pyopencl-2018.1.tar.gz (357kB)
    100% |████████████████████████████████| 358kB 2.2MB/s 
Collecting numpy (from pyopencl)
  Downloading numpy-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 104kB/s 
Collecting pytools>=2017.6 (from pyopencl)
  Downloading pytools-2017.6.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 12.5MB/s 
Collecting pytest>=2 (from pyopencl)
  Downloading pytest-3.3.2-py2.py3-none-any.whl (185kB)
    100% |████████████████████████████████| 194kB 6.8MB/s 
Collecting decorator>=3.2.0 (from pyopencl)
  Downloading decorator-4.2.1-py2.py3-none-any.whl
Collecting cffi>=1.1.0 (from pyopencl)
  Downloading cffi-1.11.4-cp27-cp27mu-manylinux1_x86_64.whl (406kB)
    100% |████████████████████████████████| 409kB 4.0MB/s 
Collecting appdirs>=1.4.0 (from pyopencl)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting six>=1.9.0 (from pyopencl)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2->pyopencl)
  Downloading py-1.5.2-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 13.4MB/s 
Requirement already up-to-date: setuptools in ./env/lib/python2.7/site-packages (from pytest>=2->pyopencl)
Collecting funcsigs; python_version < "3.0" (from pytest>=2->pyopencl)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest>=2->pyopencl)
  Downloading pluggy-0.6.0.tar.gz
Collecting attrs>=17.2.0 (from pytest>=2->pyopencl)
  Downloading attrs-17.4.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->pyopencl)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 5.9MB/s 
Building wheels for collected packages: pyopencl, pytools, pluggy, pycparser
  Running setup.py bdist_wheel for pyopencl ... done
  Stored in directory: /home/niklas/.cache/pip/wheels/73/48/43/af6e10937686feb7111d120a73b6dc3a1c4b44cecd74436e99
  Running setup.py bdist_wheel for pytools ... done
  Stored in directory: /home/niklas/.cache/pip/wheels/e0/be/05/6928439fb79d4fa316cf1cebcf9362fad025250443387a27c1
  Running setup.py bdist_wheel for pluggy ... done
  Stored in directory: /home/niklas/.cache/pip/wheels/df/44/8e/e136760ae525eac46b3e3db643ef58ff1753177b5a722b0c96
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/niklas/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pyopencl pytools pluggy pycparser
Installing collected packages: numpy, decorator, appdirs, six, pytools, py, funcsigs, pluggy, attrs, pytest, pycparser, cffi, pyopencl
  Found existing installation: numpy 1.11.0
    Not uninstalling numpy at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: decorator 4.0.6
    Not uninstalling decorator at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: appdirs 1.4.0
    Not uninstalling appdirs at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: six 1.10.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: pytools 2015.1.6
    Not uninstalling pytools at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: attrs 15.2.0
    Not uninstalling attrs at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
  Found existing installation: pyopencl 2015.1
    Not uninstalling pyopencl at /usr/lib/python2.7/dist-packages, outside environment /home/niklas/src/fut/env
Successfully installed appdirs-1.4.3 attrs-17.4.0 cffi-1.11.4 decorator-4.2.1 funcsigs-1.0.2 numpy-1.14.0 pluggy-0.6.0 py-1.5.2 pycparser-2.18 pyopencl-2018.1 pytest-3.3.2 pytools-2017.6 six-1.11.0
pip install -U pyopencl  37.77s user 2.70s system 97% cpu 41.688 total
(env) niklas@ares ~/src/fut % ~/src/futhark/.stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/futhark-pyopencl/futhark-pyopencl fact.fut && echo "100" | ./fact
0i32
```

That works.

I think it's fine to require a minimum version of pyopencl, but it would be very helpful if the futhark docs  / installation instructions could tell me what the minimum required version is.

It would also be great if the generated python script could do a run-time check for the version, and die with like `your pyopencl is too old, you need at least version X` if the version is too low.

That would make it easier to get started with futhark.

**Comment by Athas** [comment]
I agree.  I will see if I can reverse-engineer the version bound.
